# database
database:
    host: localhost
    table: facebook_message_murmured
    username: root
    password:

# server
server:
    port: 8080

# datasource configuration
spring:
    application:
        name: facebook-message-murmured
    profiles:
        active: dev
    datasource:
        username: ${database.username}
        password: ${database.password}
        url: jdbc:mysql://${database.host}:3306/${database.name}?characterEncoding=utf-8&useUnicode=true&useSSL=false&rewriteBatchedStatements=TRUE

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: false

    http:
        encoding:
            charset: UTF-8

# liquibase configuration
liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml

# schedule indicates the frequency to poll data from different source
# http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/
# 要執行排程請自行改為 true
quartz:
    enabled: false
